t_example1. [('x : nat) -> ('y : nat) -> ('z : nat) -> (= (+ (* x y) z) (+ (* x y) z))]
t_example2. [('x : nat) -> ('y : nat) -> (= 'y (+ 'x n7)) -> (= (* n2 'y) (* n2 (+ 'x n7)))]
t_example3. [('a : nat) -> ('b : nat) -> (= (s 'a) 'b) -> (= (s (s 'a)) (s 'b))]
t_add_succ_zero. [('a : nat) -> (= (+ 'a (s z)) (s 'a))]
a_zero_add. [('n : nat) -> (= (+ z 'n) 'n)]
a_add_assoc. [('a : nat) -> ('b : nat) -> ('c : nat) -> (= (+ (+ 'a 'b) 'c) (+ 'a (+ 'b 'c)))]
a_succ_add. [('a : nat) -> ('b : nat) -> (= (+ (s 'a) 'b) (s (+ 'a 'b)))]
a_succ_eq_add_one. [('n : nat) -> (= (s 'n) (+ 'n (s z)))]
m_zero_mul. [('m : nat) -> (= (* z 'm) z)]
m_mul_one. [('m : nat) -> (= (* 'm (s z)) 'm)]
