1. [('A : prop) -> ['A -> 'A]]
2. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> 'B] -> ['B -> 'C] -> ['A -> 'C]]
3. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> ['B -> 'C]] -> ['B -> ['A -> 'C]]]
4. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> ['B -> 'C]] -> [(and 'A 'B) -> 'C]]
5. [('A : prop) -> ('B : prop) -> ('C : prop) -> [(and 'A 'B) -> 'C] -> ['A -> ['B -> 'C]]]
6. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> 'B] -> [['B -> 'C] -> ['A -> 'C]]]
7. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> 'B] -> [['C -> 'A] -> ['C -> 'B]]]
8a. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> 'B] -> [(and 'A 'C) -> (and 'B 'C)]]
8b. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> 'B] -> [(and 'C 'A) -> (and 'C 'B)]]
9a. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> 'B] -> [(or 'A 'C) -> (or 'B 'C)]]
9b. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> 'B] -> [(or 'A 'C) -> (or 'B 'C)]]
10a. [('A : prop) -> ('B : prop) -> [(not 'A) -> ['A -> 'B]]]
10b. [('A : prop) -> ('B : prop) -> ['A -> [(not 'A) -> 'B]]]
11. [('A : prop) -> ('B : prop) -> ['B -> ['A -> 'B]]]
12. [('A : prop) -> ('B : prop) -> ['A -> 'B] -> [(not 'B) -> (not 'A)]]
13. [('A : prop) -> ('B : prop) -> ['A -> (not 'B)] -> ['B -> (not 'A)]]
14. [('A : prop) -> ('B : prop) -> [(not 'A) -> 'B] -> [(not 'B) -> 'A]]
15. [('A : prop) -> ('B : prop) -> [(not 'A) -> (not 'B)] -> ['B -> 'A]]
16. [('A : prop) -> ('B : prop) -> ['A -> 'B] -> ['B -> 'A] -> (iff 'A 'B)]
17a. [('A : prop) -> ('B : prop) -> (iff 'A 'B) -> ['A -> 'B]]
17b. [('A : prop) -> ('B : prop) -> (iff 'A 'B) -> ['B -> 'A]]
18a. [('A : prop) -> ('B : prop) -> (iff 'A 'B) -> 'A -> 'B]
18b. [('A : prop) -> ('B : prop) -> (iff 'A 'B) -> 'B -> 'A]
19. [('A : prop) -> (iff 'A 'A)]
20. [('A : prop) -> ('B : prop) -> (iff 'A 'B) -> (iff 'B 'A)]
21. [('A : prop) -> ('B : prop) -> ('C : prop) -> (iff 'A 'B) -> (iff 'B 'C) -> (iff 'A 'C)]
22. [('A : prop) -> ('B : prop) -> ('C : prop) -> ['A -> ['B -> 'C]] -> [(not (not 'A)) -> [(not (not 'B)) -> (not (not 'C))]]]
23. [('A : prop) -> ('B : prop) -> [(not (not ['A -> 'B]))] -> [(not (not 'A)) -> (not (not 'B))]]
24. [('A : prop) -> ('B : prop) -> ('C : prop) -> [(not (not ['A -> 'B]))] -> [(not (not ['B -> 'C]))] -> [(not (not ['A -> 'C]))]]
25. [('A : prop) -> ('B : prop) -> (iff (not (not (and 'A 'B))) (and (not (not 'A)) (not (not 'B))))]
